trigger:
  branches:
    include:
      - main  # Runs on pushes to main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: $(AZURE_SERVICE_CONNECTION)  # Service connection name
  containerRegistry: $(ACR_NAME)  # ACR URL
  imageName: $(IMAGE_NAME)  # Name for your container image
  tag: 'latest'  # Tag image
  webAppName: $(WEB_APP_NAME)  # Azure Web App name
  resourceGroup: $(RESOURCE_GROUP)  # Azure Resource Group

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: login
        containerRegistry: $(containerRegistry)
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)
          $(Build.BuildId)

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        containers: '$(containerRegistry)/$(imageName):$(tag)'

